name: quadroflow
description: "A visual organization application that combines the simplicity of the Kanban board with the fluidity of an agile workflow."

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/QuadroFlow/quadroflow_client

version: 0.1.0+1

environment:
  sdk: ^3.8.1
  flutter: ^3.32.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
